[package]
name = "magnat-headless"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
# Test negatywny T-D8: celowo wstrzyknięty niedeterminizm w jednym systemie.
chaos = []

[dependencies]
magnat-core = { workspace = true }
magnat-ecs = { workspace = true }
magnat-jobs = { workspace = true }
magnat-io = { workspace = true }
magnat-devtools = { workspace = true }
magnat-world = { workspace = true }
clap = { workspace = true }

[lints]
workspace = true
