[package]
name = "magnat-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
magnat-core = { workspace = true }
magnat-voxel = { workspace = true }
magnat-sim-snapshot = { workspace = true }
magnat-devtools = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
glam = { workspace = true }
pollster = { workspace = true }
bytemuck = { workspace = true }
log = "0.4"

[lints]
workspace = true
