[package]
name = "magnat-world"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
magnat-core = { workspace = true }
magnat-jobs = { workspace = true }
magnat-voxel = { workspace = true }
smallvec = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
zstd = { workspace = true }
ron = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[lints]
workspace = true
